In [1]:
import pandas as pd
import numpy as np

x = pd.read_csv('2010825.txt', delimiter = "\t", header = None)
print(x, x.shape)

             0        1
0     -84.5152  19.1264
1     -76.6465  20.2474
2     -76.6615  20.3420
3     -76.6415  20.2342
4     -76.6472  20.2203
...        ...      ...
16254 -87.7532  14.8606
16255 -75.6542   9.8984
16256 -80.6016  22.0641
16257 -80.3845  21.9461
16258 -75.4638  10.1300

[16259 rows x 2 columns] (16259, 2)


In [8]:
M = np.array([[0,0]])
print(M.shape)
col_3 = np.zeros(16259).reshape(16259, 1)
# print(col_3.shape)

# Stacking the two arrays horizontally 
X = np.concatenate((x, col_3), axis=1)
print(X, X.shape)


(1, 2)
[[-84.5152  19.1264   0.    ]
 [-76.6465  20.2474   0.    ]
 [-76.6615  20.342    0.    ]
 ...
 [-80.6016  22.0641   0.    ]
 [-80.3845  21.9461   0.    ]
 [-75.4638  10.13     0.    ]] (16259, 3)


In [ ]:
# part F to compute error 9.73

centroid_L2 = {1:0, 2:0, 3:0, 4:0, 5:0}
centroid_XY = {1:[], 2:[], 3:[], 4:[], 5:[]}
# centroid_L2_counter = {1:0, 2:0, 3:0, 4:0, 5:0}
M = np.array([[0,0]])
# M=np.copy(X[0:5,0:X.shape[1]-1])

for idx, i in enumerate(X[:,0:2]):  # iterate over 10 rows of X, col 1 and col 2

    l2_norm = np.sqrt(np.square(i[0] - M[:,0]) + np.square(i[1] - M[:,1])) # get the l2 norm value
    centroid_L2[np.argmin(l2_norm)+1] += np.amin(l2_norm)
    centroid_XY[np.argmin(l2_norm)+1].append(i)
    X[idx, 2] = np.argmin(l2_norm) 
#     centroid_L2_counter[np.argmin(l2_norm)+1] += 1

print(f'X first 15 rows:\n{X[:15, ]}')
print()
print(f'X shape:{X.shape}')
# print(f'centroid_L2\n{centroid_L2}')
print()
# print(f'centroid_L2_counter\n{centroid_L2_counter}\n') 

c1_coord_update = np.array([np.mean([i[0] for i in centroid_XY.get(1)]), np.mean([i[1] for i in centroid_XY.get(1)])])
c2_coord_update = np.array([np.mean([i[0] for i in centroid_XY.get(2)]), np.mean([i[1] for i in centroid_XY.get(2)])])
c3_coord_update = np.array([np.mean([i[0] for i in centroid_XY.get(3)]), np.mean([i[1] for i in centroid_XY.get(3)])])
c4_coord_update = np.array([np.mean([i[0] for i in centroid_XY.get(4)]), np.mean([i[1] for i in centroid_XY.get(4)])])
c5_coord_update = np.array([np.mean([i[0] for i in centroid_XY.get(5)]), np.mean([i[1] for i in centroid_XY.get(5)])])
print(c1_coord_update, c2_coord_update, c3_coord_update, c4_coord_update, c5_coord_update)

In [6]:
def errCompute(X, M):

    l2 = np.linalg.norm(X[:, :2] - M[X[:, 2].astype(int)], axis=1)
    print(M[X[:, 2].astype(int)].shape)
    return np.mean(l2)

print(f'X:\n{X[:10, ]}, {X.shape}')
# M=np.copy(X[0:5,0:X.shape[1]-1])
print(f'M:\n', M)
errCompute(X, M)

X:
[[-84.5152  19.1264   0.    ]
 [-76.6465  20.2474   0.    ]
 [-76.6615  20.342    0.    ]
 [-76.6415  20.2342   0.    ]
 [-76.6472  20.2203   0.    ]
 [-76.6409  20.2693   0.    ]
 [-64.9945   9.5567   0.    ]
 [-83.1603  23.0362   0.    ]
 [-82.5861  23.6002   0.    ]
 [-80.3366  22.236    0.    ]], (16259, 3)
M:
 [[0 0]]
(16259, 2)


86.62495736289799

In [9]:
## K-means computation function starts here ... 
# print(f'X before:\n {X[:15]}\n')
M = np.copy(X[0:5,0:X.shape[1]-1])
print(f'M at the start:\n {M}]\n')
print(f'M shape: {M.shape[0]}\n')

for count in range(30):
    centroid_XY = {i:[] for i in range(0,M.shape[0])} # create dict for xy_coords, K = M.shape[0]
    for idx, i in enumerate(X[:,0:2]):                # iterate over 10 rows of X, col 1 and col 2
        l2_norm = np.sqrt(np.square(i[0] - M[:,0]) + np.square(i[1] - M[:,1])) # get the l2 norm value
        X[idx, 2] = np.argmin(l2_norm)                                         # populates col_2 with cluster IDs 
        centroid_XY[np.argmin(l2_norm)].append(i)                              # append xy_coord to their k-v pair
#### ------------------------------------------------------------------ #####
    old = M                                            # assign current M centroid matrix to old var b4 update M
    yoyo = [np.array(i) for i in centroid_XY.values()] # extract xy coords of each centroid into a list
    M = np.array([0,0])  # dummy array for vstacking purpose
    for xy in yoyo:      # for each pair of xy_coord in list
        x_pts = xy.T[0]  # get all x_coords of a centroid
        y_pts = xy.T[1]  # get all y_coords of a centroid
        row = np.array([np.mean(x_pts), np.mean(y_pts)]) # assign xy_mean pairs to row
        M = np.vstack((M, row)) # create M matrix
    M = M[1:]                   # get rid of dummy array
#### ------------------------------------------------------------------ #####
    print(f'M after {count+1} epoch:\n{M}\n')
    
    if np.array_equal(old, M):  # if no change in centroids' XY coords, break loop 
        print(f'Centroids stablized after {count} epochs')
        break
# print(f"X after:\n {X[:15]}")

M at the start:
 [[-84.5152  19.1264]
 [-76.6465  20.2474]
 [-76.6615  20.342 ]
 [-76.6415  20.2342]
 [-76.6472  20.2203]]]

M shape: 5

M after 1 epoch:
[[-90.49390051  21.02879994]
 [-76.56876923  20.2852    ]
 [-78.4862675   23.80770642]
 [-75.77208511  20.08975213]
 [-72.1762039    8.76110395]]

M after 2 epoch:
[[-95.08619499  20.04095909]
 [-77.90867745  20.05257663]
 [-81.47717345  24.89637199]
 [-75.21811255  16.11175059]
 [-73.0128578    8.14005597]]

M after 3 epoch:
[[-97.67826985  20.53838907]
 [-80.09429143  19.71696707]
 [-82.3028632   25.2581391 ]
 [-79.55338965  13.30936534]
 [-72.36853251   7.86863221]]

M after 4 epoch:
[[-99.76214666  21.85407224]
 [-79.05754415  21.22876499]
 [-82.37493854  25.54742293]
 [-83.88645672  13.03292921]
 [-71.09123486   7.72165806]]

M after 5 epoch:
[[-101.05596915   22.77247799]
 [ -79.11839733   21.19946827]
 [ -82.56420437   25.78578055]
 [ -85.58298424   13.33401744]
 [ -71.32789807    7.79187594]]

M after 6 epoch:
[[-103.17351806 

In [ ]:
# centroid_XY
yoyo = [np.array(i) for i in centroid_XY.values()]
i=0
haha = np.array([0,0])
for xy in yoyo:
    x_pts = xy.T[0]
    y_pts = xy.T[1]
    print(f'yoyo[{i}]:\n{xy}\n')
    print(f'x_pts: {x_pts}')
    print(f'y_pts: {y_pts}\n')
    print(f'x_mean: {np.mean(x_pts)}')
    print(f'y_mean: {np.mean(y_pts)}\n')
    i+=1
    row = np.array([np.mean(x_pts), np.mean(y_pts)])
    haha = np.vstack((haha, row))
print(haha[1:])

In [10]:
def errCompute(X, M):

    l2 = np.linalg.norm(X[:, :2] - M[X[:, 2].astype(int)], axis=1)
    return np.mean(l2)

print(f'X:\n{X[:10, ]}, {X.shape}')
print(f'M:\n',M)
errCompute(X, M)  # 

X:
[[-84.5152  19.1264   1.    ]
 [-76.6465  20.2474   1.    ]
 [-76.6615  20.342    1.    ]
 [-76.6415  20.2342   1.    ]
 [-76.6472  20.2203   1.    ]
 [-76.6409  20.2693   1.    ]
 [-64.9945   9.5567   4.    ]
 [-83.1603  23.0362   2.    ]
 [-82.5861  23.6002   2.    ]
 [-80.3366  22.236    1.    ]], (16259, 3)
M:
 [[-105.19604652   25.33132344]
 [ -79.39863196   21.23281229]
 [ -82.67640192   26.06156976]
 [ -89.16882233   15.14357792]
 [ -72.13285047    8.21465361]]


4.006100077883563

In [ ]:
dict = {0: [111, 222, 333, 444], 1: [1111, 2222, 3333, 4444], 2: [1, 2, 3, 4]} 

yoyo = [np.array(i) for i in dict.values()]
print(f'yoyo: {yoyo}')
print(f'yoyo type: {type(yoyo)}')

np.mean(yoyo[0])